name: Continuous Integration
on: [push, pull_request]
jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5 SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 5.0.x
      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.x
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5 SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 5.0.x
      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.x
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  macos-build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5 SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 5.0.x
      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.x
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
